import type { User } from "./types";

export const mockedUsers: User[] = [
  {
    fullName: "Joseph Mbarga",
    phone: "+237 6 99 12 45 78",
    birthDate: "14/03/1992",
    birthPlace: "Yaoundé",
    placeName: "Carrefour Nlongkak",
    district: "Nlongkak",
    city: "Yaoundé",
    country: "Cameroun",
    status: "Actif",
    kyc: "Validé",
    kycFieldsCompleted: 11,
    kycFieldsTotal: 11,
    kycFiles: { selfie: true, cniFront: true, cniBack: true },
    subscription: "Standard",
    subscriptionPrice: "1 000 FCFA",
    miniSite: "Actif",
    wallet: "245 000 FCFA",
  },
  {
    fullName: "Clarisse Ndogmo",
    phone: "+237 6 74 88 20 11",
    birthDate: "28/08/1995",
    birthPlace: "Douala",
    placeName: "Bonamoussadi entrée école",
    district: "Bonamoussadi",
    city: "Douala",
    country: "Cameroun",
    status: "Actif",
    kyc: "En attente",
    kycFieldsCompleted: 11,
    kycFieldsTotal: 11,
    kycFiles: { selfie: true, cniFront: true, cniBack: true },
    subscription: "Standard",
    subscriptionPrice: "1 000 FCFA",
    miniSite: "Actif",
    wallet: "82 500 FCFA",
  },
  {
    fullName: "Christian Fotso",
    phone: "+237 6 55 41 90 33",
    birthDate: "05/12/1988",
    birthPlace: "Bafoussam",
    placeName: "Marché A",
    district: "Tamdja",
    city: "Bafoussam",
    country: "Cameroun",
    status: "Inactif",
    kyc: "Incomplet",
    kycFieldsCompleted: 8,
    kycFieldsTotal: 11,
    kycFiles: { selfie: true, cniFront: false, cniBack: false },
    subscription: "Standard",
    subscriptionPrice: "1 000 FCFA",
    miniSite: "Inactif",
    wallet: "0 FCFA",
  },
];